apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp
    labels:
        app: myapp
        version: 0.0.1
spec:
    replicas: 3
    selector:
        matchLabels:
            app: myapp
            version: 0.0.1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
    template:
        metadata:
            name: myapp
            labels:
                app: myapp
                version: 0.0.1
        spec:
            containers:
                - name: myapp
                  image: gkiran04/mywebapp:latest
                  ports:
                      - name: myapp
                        containerPort: 8080