apiVersion: v1
kind: Service
metadata:
  name: myapp
  nameSpace: default
  labels:
      app: myapp
      version: 0.0.1
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 8080
    targetPort: 8080
